### ISSUE TITLE
One ServiceLocator by deployed Verticle

### ISSUE THREAD

**Issue by hosuaby** [englishtown/vertx-hk2#5]
Hello,
`HK2VerticleLoader` creates a new `ServiceLocator` for every deployed verticle as states following code:
```java
// Each verticle factory will have it's own service locator instance
// Passing a null name will not cache the locator in the factory
locator = ServiceLocatorFactory.getInstance().create(null, parent);
```
That means that beans can not be shared if multiple Verticles are deployed programatically:
```java
vertx.deployVerticle("java-hk2:my.awesome.verticle");
vertx.deployVerticle("java-hk2:my.awesome.another_verticle");
```
`HK2VerticleFactory` has attribute `ServiceLocator locator` but it always null.
Isn't it would be better to have a single ServiceLocator in HK2VerticleFactory shared between all verticles ?

**Comment by adrianluisgonzalez** [comment]
Each verticle receives its own `ServiceLocator` instance for a couple reasons:
* When running services with `IsolatedClassLoader` this is necessary, different jar version can be loaded
* When using the vert.x redeploy feature you want to ensure new instances are created (and it could be a new version of a jar)

However, if you do want to share instances across verticles that can be achieved by programmatically setting the `ServiceLocator` on the factory as you mention.  Each verticle created will still have its own locator, but it will use that as the parent locator.  I was not able to come up with a good way to do it via configuration since it is not running in a vert.x context at that point, configuration is not available.

Does that makes sense?  Any suggestions on alternative approaches?  

It would probably be good to add an explanation in the read me.

**Comment by hosuaby** [comment]
Thanks for your answer. It answers my current problem. I am starting working closely with Vert.x and HK2. If I have some suggestions or ideas I will not hesitate to propose via issues or pull-requests.
